Repository ReachFive/identity-web-core-sdk, pull requests merged in 2019-03, with the labels that each got.

#5 fix: correct the typography of the `oldPassword` argument
  src/main/apiClient.ts
  src/main/main.ts
Labels: fix, require review

#7 Fix the typography of the `oldPassword` argument
  src/main/apiClient.ts
  src/main/main.ts
Labels: fix, require review

#8 feature: create a `PUBLISH.md` file and update the `README.md`
  PUBLISH.md
  README.md
Labels: feature, require review

#9 fix: add a build job in the circleci config
  .circleci/config.yml
Labels: fix, require review

#10 feature: add a circleci configuration
  .circleci/config.yml
  package.json
Labels: feature, require review

#11 fix: fix the regex for the 'deploy-alpha' task
  .circleci/config.yml
Labels: fix, require review

#12 fix: update the deploy-alpha regex to include the complete alpha's number
  .circleci/config.yml
Labels: fix, legacy, require review

#13 fix: fix the circleci config to publish automatically the library on npm
  .circleci/config.yml
  PUBLISH.md
  README.md
  package.json
Labels: fix, legacy, require review

#14 fix: fix the circleci configuration and update the PUBLISH.md file
  .circleci/config.yml
  PUBLISH.md
Labels: fix

#15 feature: some enhancements
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: feature, require review

#17 release: release v1.1.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release, require review

#16 fix: update publish guide
  PUBLISH.md
  README.md
Labels: fix, require review

#19 release 1.2.0
  package-lock.json
  package.json
Labels: release

#21 fix: improve the presentation of the release guide
  RELEASE.md
Labels: documentation, fix, require review
