Repository ReachFive/identity-web-core-sdk, pull requests merged in 2019-07, with the labels that each got.

#45 Add default scope
  src/main/apiClient.ts
  src/main/authOptions.ts
Labels: feature, require review

#44 Adds default scopes for the authorize endpoint
  src/main/apiClient.ts
  src/main/apiClientConfig.ts
  src/main/authOptions.ts
Labels: feature, legacy, require review

#46 Release v0.1.0-alpha.18
  package-lock.json
  package.json
Labels: release
