Repository ReachFive/identity-web-core-sdk, pull requests merged in 2019-12, with the labels that each got.

#73 Errors with PKCE methods for the UMD bundle
  package-lock.json
  package.json
  src/main/pkceService.ts
  src/utils/base64.ts
Labels: fix

#74 Release v1.9.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#75 Snake case transformation for consents and custom fields
  .gitignore
  src/lib/transformObjectProperties.ts
Labels: fix, legacy

#76 Release v0.1.0-alpha.22
  CHANGELOG.md
  package-lock.json
  package.json
Labels: legacy, release, require review
