Repository ReachFive/identity-web-core-sdk, pull requests merged in 2019-08, with the labels that each got.

#47 feature: Support of Credentials Management API
  package-lock.json
  package.json
  src/main/apiClient.ts
  src/main/main.ts
  tsconfig.json
Labels: feature, require review

#48 Release/v1.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#42 Redirect url for more endpoints
  src/main/apiClient.ts
  src/main/main.ts
Labels: legacy

#49 Release v0.1.0-alpha.19
  CHANGELOG.md
  package-lock.json
  package.json
Labels: legacy, release

#50 Downgrade the lodash dependency's version
  package-lock.json
  package.json
Labels: fix

#51 Revert "Update lodash dependency" #2
  package.json
Labels: fix

#52 Release v0.1.0-alpha.20
  CHANGELOG.md
  package-lock.json
  package.json
Labels: legacy, release

#53 Update the RELEASE.md file
  RELEASE.md
Labels: fix

#54 Update the RELEASE.md file
  RELEASE.md
Labels: fix, legacy
