Repository ReachFive/identity-web-core-sdk, pull requests merged in 2019-09, with the labels that each got.

#56 feature: Support of Credentials Management API for signup
  src/main/apiClient.ts
  src/main/models.ts
Labels: feature

#57 add updateEmail.redirectUrl
  src/main/apiClient.ts
  src/main/main.ts
Labels: fix, require review

#58 Release v1.7.0
  CHANGELOG.md
  package.json
Labels: release

#59 fix custom fields and cosents case conversions
  package-lock.json
  src/utils/transformObjectProperties.ts
Labels: fix

#62 Release v1.7.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
