Repository ReachFive/identity-web-core-sdk, pull requests merged in 2019-06, with the labels that each got.

#24 feature: update the signature of the `loginWithPassword` method
  .gitignore
  src/main/__tests__/apiClientCordova.spec.ts
  src/main/__tests__/loginWithPassword.spec.ts
  src/main/apiClient.ts
Labels: feature

#25 feature: update the signature of the `loginWithPassword` method (master)
  .gitignore
  src/main/__tests__/apiClientCordova.spec.ts
  src/main/__tests__/loginWithPassword.spec.ts
  src/main/apiClient.ts
Labels: feature

#26 Release v1.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#22 Add prettier
  .prettierrc
  package-lock.json
  package.json
  src/main/__tests__/apiClient.spec.ts
  src/main/__tests__/apiClientCordova.spec.ts
  src/main/__tests__/authOptions.spec.ts
  src/main/__tests__/checkSession.spec.ts
  src/main/__tests__/loginFromSession.spec.ts
  src/main/__tests__/loginWithPassword.spec.ts
  src/main/__tests__/loginWithSocialProvider.spec.ts
  src/main/__tests__/refreshTokens.spec.ts
  src/main/__tests__/remoteSettingsResolving.spec.ts
  src/main/__tests__/requestPasswordReset.spec.ts
  src/main/__tests__/signup.spec.ts
  src/main/__tests__/testHelpers.ts
  src/main/__tests__/winchanMocker.ts
  src/main/ajax.ts
  src/main/apiClient.ts
  src/main/authOptions.ts
  src/main/authResult.ts
  src/main/global.d.ts
  src/main/httpClient.ts
  src/main/identityEventManager.ts
  src/main/main.ts
  src/main/models.ts
  src/main/providerPopupSize.ts
  src/main/urlParser.ts
  src/utils/__tests__/eventManager.spec.ts
  src/utils/__tests__/transformObjectProperties.spec.ts
  src/utils/base64.ts
  src/utils/eventManager.ts
  src/utils/logger.ts
  src/utils/obj.ts
  src/utils/promise.ts
  src/utils/queryString.ts
  src/utils/transformObjectProperties.ts
Labels: enhancement

#27 fix: minor enhancements
  RELEASE.md
  src/main/__tests__/loginWithPassword.spec.ts
  src/main/apiClient.ts
Labels: enhancement, require review

#28 add redirect argument
  src/main/apiClient.ts
  src/main/main.ts
Labels: feature

#31 specify email redirect url - legacy
  src/main/apiClient.ts
  src/main/main.ts
Labels: feature, fix

#29 Reset and update password with phone number
  .gitignore
  src/main/apiClient.ts
  src/main/main.ts
Labels: feature

#30 Reset and update password with phone number (legacy)
  .gitignore
  src/main/apiClient.ts
  src/main/main.ts
Labels: feature, legacy

#32 Feature/pkce support legacy
  src/lib/base64.ts
  src/main/apiClient.ts
  src/main/apiClientConfig.ts
  src/main/main.ts
  src/main/pkceService.ts
Labels: feature, require review

#36 Add pkce support
  src/main/apiClient.ts
  src/main/main.ts
  src/main/pkceService.ts
  src/utils/base64.ts
Labels: feature, require review

#41 redirect url for more endpoints
  src/main/apiClient.ts
  src/main/main.ts
Labels: feature
