Repository ReachFive/identity-web-core-sdk, pull requests merged in 2020-10, with the labels that each got.

#125 Delete the close event condition
  src/main/apiClient.ts
Labels: bug

#126 Release v1.17.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#127 PKCE improvements
  CHANGELOG.md
  src/main/__tests__/apiClient.spec.ts
  src/main/__tests__/apiClientCordova.spec.ts
  src/main/__tests__/checkSession.spec.ts
  src/main/__tests__/loginFromSession.spec.ts
  src/main/__tests__/loginWithPassword.spec.ts
  src/main/__tests__/loginWithSocialProvider.spec.ts
  src/main/__tests__/remoteSettingsResolving.spec.ts
  src/main/__tests__/signup.spec.ts
  src/main/__tests__/testHelpers.ts
  src/main/apiClient.ts
  src/main/authOptions.ts
  src/main/main.ts
  src/main/models.ts
  src/main/pkceService.ts
Labels: enhancement, merge ready

#129 Release v1.18.0
  CHANGELOG.md
  RELEASE.md
  package-lock.json
  package.json
Labels: release
