Repository ReachFive/identity-web-core-sdk, pull requests merged in 2020-09, with the labels that each got.

#111 Ajout d'un paramètre purpose lors du reset password.
  src/main/apiClient.ts
Labels: enhancement, require testing

#115 Revert "Ajout d'un paramètre purpose lors du reset password."
  src/main/apiClient.ts
Labels: revert

#113 Enable SDK users to obtain AuthResult using web messages instead of redirection
  src/main/__tests__/apiClient.spec.ts
  src/main/__tests__/apiClientCordova.spec.ts
  src/main/__tests__/checkSession.spec.ts
  src/main/__tests__/loginFromSession.spec.ts
  src/main/__tests__/loginWithPassword.spec.ts
  src/main/__tests__/loginWithSocialProvider.spec.ts
  src/main/__tests__/signup.spec.ts
  src/main/__tests__/testHelpers.ts
  src/main/apiClient.ts
  src/main/authOptions.ts
  src/main/authResult.ts
  src/main/global.d.ts
  src/main/main.ts
  src/utils/queryString.ts
Labels: enhancement

#117 Release v1.16.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#118 Use the same deploy job than the UI SDK
  .circleci/config.yml
Labels: bug

#119 Implement signup for the FIDO2 flow
  src/main/apiClient.ts
  src/main/main.ts
  src/main/models.ts
  src/main/webAuthnService.ts
Labels: enhancement

#120 Release v1.17.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#121 Use the env variables in the CircleCi "reachfive" context
  .circleci/config.yml
Labels: bug

#122 Release v1.17.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#123 Upgrade dependencies
  package-lock.json
  package.json
  src/main/__tests__/apiClient.spec.ts
  src/main/__tests__/apiClientCordova.spec.ts
  src/main/__tests__/checkSession.spec.ts
  src/main/__tests__/loginFromSession.spec.ts
  src/main/__tests__/loginWithPassword.spec.ts
  src/main/__tests__/loginWithSocialProvider.spec.ts
  src/main/__tests__/refreshTokens.spec.ts
  src/main/__tests__/remoteSettingsResolving.spec.ts
  src/main/__tests__/requestPasswordReset.spec.ts
  src/main/__tests__/sendEmailVerification.spec.ts
  src/main/__tests__/sendPhoneNumberVerification.spec.ts
  src/main/__tests__/signup.spec.ts
  src/main/__tests__/testHelpers.ts
  src/main/authOptions.ts
Labels: dependencies
