Repository ReachFive/identity-web-core-sdk, pull requests merged in 2020-02, with the labels that each got.

#80 returnTo for password reset et signup
  src/main/apiClient.ts
Labels: feature

#81 Release v1.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#82 Test the CircleCi 'deploy-release' job
  .circleci/config.yml
  package-lock.json
  package.json
Labels: fix, for testing

#83 Revert "Test the CircleCi 'deploy-release' job (#82)"
  .circleci/config.yml
  package-lock.json
  package.json
Labels: for testing
