Repository ReachFive/identity-web-core-sdk, pull requests merged in 2020-05, with the labels that each got.

#91 Add `verificationCode` in the typings of the `verifyPasswordless` method
  src/main/apiClient.ts
  src/main/main.ts
Labels: bug

#92 Release v1.12.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#93 Add two routes : send-email-verification and send-phone-number-verification
  src/main/__tests__/sendEmailVerification.spec.ts
  src/main/__tests__/sendPhoneNumberVerification.spec.ts
  src/main/apiClient.ts
  src/main/main.ts
Labels: enhancement

#94 Release v1.13.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
