Repository ReachFive/identity-web-core-sdk, pull requests merged in 2020-04, with the labels that each got.

#86 Use persistent field in remember me
  .gitignore
  src/main/__tests__/authOptions.spec.ts
  src/main/apiClient.ts
  src/main/authOptions.ts
Labels: enhancement, require review

#87 Release v1.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#88 Move persistent field in authOptions for remember me
  src/main/apiClient.ts
Labels: enhancement

#90 Release v1.12.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
