Repository ReachFive/identity-web-core-sdk, pull requests merged in 2020-06, with the labels that each got.

#95 Point to the correct doc in CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#97 Implement the `addNewWebAuthnDevice` method
  src/main/apiClient.ts
  src/main/main.ts
  src/main/webAuthnService.ts
Labels: enhancement

#99 Implement the `loginWithWebAuthn` method
  src/main/apiClient.ts
  src/main/main.ts
  src/main/webAuthnService.ts
Labels: enhancement

#100 Update the `addNewWebAuthnDevice` method
  src/main/apiClient.ts
  src/main/webAuthnService.ts
Labels: bug

#101 Release v1.14.0-beta.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#102 Implement the list/delete WebAuthn methods
  src/main/apiClient.ts
  src/main/httpClient.ts
  src/main/main.ts
  src/main/webAuthnService.ts
Labels: enhancement

#103 Throw an error if `navigator.credentials` is not available
  src/main/apiClient.ts
Labels: bug

#104 Release v1.14.0-beta.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#98 Add signup data endpoint
  src/main/apiClient.ts
  src/main/main.ts
  src/main/models.ts
Labels: enhancement

#105 Update the error message when the CM API is not available
  src/main/apiClient.ts
Labels: enhancement
