Repository ReachFive/identity-web-core-sdk, pull requests merged in 2020-11, with the labels that each got.

#130 Return the object reference from InAppBrowser within Cordova context
  CHANGELOG.md
  package-lock.json
  package.json
  src/main/__tests__/apiClientCordova.spec.ts
  src/main/apiClient.ts
  src/main/global.d.ts
  src/main/main.ts
  tsconfig.json
Labels: cordova, enhancement

#131 Add the `returnToAfterEmailConfirmation` in `signupWithWebAuthn` method
  src/main/apiClient.ts
  src/main/webAuthnService.ts
Labels: bug

#132 Pass the auth parameter to the `verifyPasswordless` method
  src/main/main.ts
Labels: bug

#133 Release v1.18.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
