Repository ReachFive/identity-web-core-sdk, pull requests merged in 2021-01, with the labels that each got.

#139 Add a token parameter to verify reCAPTCHA v3 in /password/login
  src/main/apiClient.ts
Labels: enhancement, require review

#140 Release v1.20.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#138 Remove Instagram as social provider
  CHANGELOG.md
  src/main/providerPopupSize.ts
Labels: merge ready
