Repository ReachFive/identity-web-core-sdk, pull requests merged in 2024-01, with the labels that each got.

#215 [CA-3237] Add new variable locale
  src/main/httpClient.ts
  src/main/main.ts
Labels: require review

#219 Release v1.32.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#220 TypeScript v4 -> v5
  package-lock.json
  package.json
  rollup.config.js
  src/main/oAuthClient.ts
  src/main/webAuthnClient.ts
  src/main/webAuthnService.ts
  src/utils/logger.ts
  tsconfig.json
Labels: require review, dependencies

#221 [CA-3366] Add a timeout to solve promise resolving problem in verifyPasswordless
  src/main/oAuthClient.ts
Labels: require review

#223 Release v1.32.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#222 [CA-1100] Replace TSLint by ESLint
  .circleci/config.yml
  .eslintrc.json
  jest.config.json
  package-lock.json
  package.json
  src/main/__tests__/helpers/oauthHelpers.ts
  src/main/__tests__/helpers/testHelpers.ts
  src/main/__tests__/helpers/winchanMocker.ts
  src/main/__tests__/loginWithPassword.spec.ts
  src/main/ajax.ts
  src/main/authResult.ts
  src/main/global.d.ts
  src/main/httpClient.ts
  src/main/models.ts
  src/main/oAuthClient.ts
  src/utils/base64.ts
  src/utils/eventManager.ts
  src/utils/jwt.ts
  src/utils/transformObjectProperties.ts
  tsconfig.json
  tslint.json
Labels: enhancement, require review, dependencies
