Repository ReachFive/identity-web-core-sdk, pull requests merged in 2025-02, with the labels that each got.

#244 [CA-4423] Add method verifyEmail
  CHANGELOG.md
  src/main/main.ts
  src/main/profileClient.ts
Labels: require review

#250 Transform rawRequest to an async function
  src/main/httpClient.ts
Labels: require review

#246 Remplace lodash's method with custom implementation
  .eslintrc.json
  package-lock.json
  package.json
  src/main/__tests__/helpers/oauthHelpers.ts
  src/main/__tests__/helpers/testHelpers.ts
  src/main/__tests__/matchers/index.ts
  src/main/authOptions.ts
  src/main/httpClient.ts
  src/main/oAuthClient.ts
  src/main/scopeHelper.ts
  src/utils/__tests__/utils.spec.ts
  src/utils/eventManager.ts
  src/utils/queryString.ts
  src/utils/transformObjectProperties.ts
  src/utils/utils.ts
  tsconfig.json
Labels: require review, dependencies

#251 Release v1.35.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#252 Release v1.35.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/main/oAuthClient.ts
Labels: release

#253 [CA-4612] Récupérer le cookie trusted device (RBA) sur l'appel LoginWithPassord
  src/main/oAuthClient.ts
Labels: bug, require review

#254 Release v1.35.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#255 Release v1.35.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/main/oAuthClient.ts
Labels: release

#256 Add banner comment in build package
  rollup.config.js
Labels: require review

#258 Release v1.35.4
  CHANGELOG.md
  package-lock.json
  package.json
  src/main/oAuthClient.ts
Labels: release
